# Pauli Matrices

파울리 행렬의 아이겐밸류와 아이겐벡터를 구하시오.

$$ s_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad
s_y = \begin{pmatrix} 0 & -j \\ j & 0 \end{pmatrix}, \quad
s_z  = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}. $$

In [21]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

sx=np.array([[0,1],[1,0]])
ex=np.linalg.eig(sx)

ex

(array([ 1., -1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [22]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

j=1j
sy=np.array([[0,-j],[j,0]])
ey=np.linalg.eig(sy)

ey

(array([ 1.+0.j, -1.+0.j]),
 array([[-0.        -0.70710678j,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        -0.70710678j]]))

In [23]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

sz=np.array([[1,0],[0,-1]])
ez=np.linalg.eig(sz)

ez

(array([ 1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

# Normal Modes

용수철 상수가 $k$인 용수철에 연결된 두 개의 물체의 노말 모드를 구해보자. 두 개의 물체의 운동방정식은 다음으로 주어진다.$$ -m w^2 x_1 = -2kx_1 +k x_2, \\
-m w^2 x_2 = k x_1 - 2 k x_2.$$

eigenfrequencies $w$는 다음의 행렬식을 통해 구할 수 있다.$$ \frac{k}{m w^2} \begin{pmatrix} 2 & -1 \\ -1 & 2 \end{pmatrix} 
\begin{pmatrix} x_1 \\ x_2 \end{pmatrix}=
\lambda \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} $$

1. 고윳값

In [24]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

s1=np.array([[2,-1],[-1,2]])
e1=np.linalg.eig(s1)

e1

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

따라서 eigenfrequencies는$$ w_1 = \sqrt{\frac{k}{m}}, \quad w_2 = \sqrt{\frac{3k}{m}}. $$

위에서 구한 아이겐벡터와 아이겐밸류의 의미를 설명하여라.

: 행렬식을 0으로 두고 방정식을 풀어냈을 때의 해가 고유진동수이다. 아이겐벨류가 3과 1이고, 그것들을 각각 람다에 대입해 풀면
$$ w_1 = \sqrt{\frac{k}{m}}, \quad w_2 = \sqrt{\frac{3k}{m}}. $$
위와 같은 형태가 나온다.

진동수에 위에서 구한 값을 대입하면 x1과 x2의 비율을 알 수 있다.
람다가 1일 경우, kx1=kx2이므로 x1=x2 이다.
람다가 3일 경우, -kx1=kx2이므로 -x1=x2 이다.
따라서 $$ \begin{pmatrix} 1 & -1 \\ 1 & 1 \end{pmatrix}, \quad $$이 되며, x1과 x2의 크기를 더하고 루트를 씌워준 후 나누어주면 위에서 구한 아이겐벡터를 구해낼 수 있다.